export * from './post/post.repository';
export * from './user/user.repository';
export * from './post/post.repository';
export * from './like/like.repository';
export * from './follow/follow.repository';
export * from './comment/comment.repository';
export * from './prisma-repository.module';
export * from './prisma-repository.factory';
export * from './prisma-repository.registry';
