version: '3'

services:

  code_health:
    build: 
      context: .
      dockerfile: Dockerfile.ci
    entrypoint: ["npm", "run", "code:ci"]
    depends_on:
      - mongo
    external_links:
      - "host.docker.internal"

  mongo:
    image: mongo
    command: ['--replSet', 'rs0']
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root 
    volumes:
      - ./.docker/mongo-data:/data/db
    external_links:
      - "host.docker.internal"

