FROM node:18-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /home/node/app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build && npx prisma generate

#CMD ["npm", "run", "start"]
