FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl

USER node
WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
RUN npm ci

COPY --chown=node:node . .

RUN npx prisma generate && npm run format:fix && npm run lint:fix

#CMD ["npm", "run", "start"]
