version: '3'

services:

  app:
    build: .
    entrypoint: ["npm", "run", "start:docker"]
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - mongo

  code_health:
    build: 
      context: .
      dockerfile: Dockerfile.ci
    entrypoint: ["npm", "run", "code:ci"]
    depends_on:
      - app
