version: '3'

services:
  
  app:
    build: .
    entrypoint: ["npm", "run", "start:docker"]
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  test:
    build: .
    restart: on-failure
    entrypoint: ["npm", "run", "test:docker"]
    volumes:
      - .:/home/node/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - ./.docker/mongo-data:/data/db

