version: '3'

services:
  
  code_health:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: ["npm", "ci", "&&", "npm", "run", "code:ci"]
    volumes:
      - .:/home/node/app
    
