version: '3'

services:
  
  app:
    build: .
    entrypoint: ["npm", "run", "start:docker"]
    ports:
      - "3004:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - mongo
    external_links:
      - "host.docker.internal"

  test:
    build: .
    entrypoint: ["npm", "run", "test:docker"]
    volumes:
      - .:/home/node/app
    depends_on:
      - app
    external_links:
      - "host.docker.internal"

  mongo:
    image: mongo:latest
    command: ['--replSet', 'rs0']
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - ./.docker/mongo-data:/data/db
    external_links:
      - "host.docker.internal"


  mongo-express:
    image: mongo-express
    restart: on-failure  
    ports:  
      - 8081:8081
    env_file: .env
    depends_on:
      - mongo
    external_links:
      - "host.docker.internal"

