version: '3'

services:
  
  app:
    build: .
    entrypoint: ["npm", "run", "start:docker"]
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - mongo

  test:
    build: .
    entrypoint: ["npm", "run", "test:docker"]
    volumes:
      - .:/home/node/app
    depends_on:
      - app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - ./.docker/mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:  
      - 8081:8081
    env_file: .env
    depends_on:
      - mongo
