version: '3'

services:
  
  app:
    build: .
    entrypoint: ["npm", "run", "start:docker"]
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  test:
    build: .
    restart: on-failure
    entrypoint: ["npm", "run", "test:docker"]
    volumes:
      - .:/home/node/app
