import { CRYPTOGRAPHY_ALGORITHM_REGISTRY } from './algorithm/algorithm.registry';

export const CRYPTOGRAPHY_REGISTRY = {
  ALGORITHM: CRYPTOGRAPHY_ALGORITHM_REGISTRY,
  TURING: Symbol.for('MODULE:SECURITY.CRYPTOGRAPHY.TURING'),
};
