export const CRYPTOGRAPHY_ALGORITHM_REGISTRY = {
  HASH: {
    ARGON: { 2: Symbol.for('MODULE:SECURITY:CRYPTOGRAPHY:ALGORITHM:ARGON2') },
  },
  IV: {
    CRYPTO: Symbol.for('MODULE:SECURITY:CRYPTOGRAPHY:ALGORITHM:CRYPTO'),
  },
};
