#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint:fix
npm run format:fix

docker-compose down
docker compose -f docker-compose.ci.yaml up --abort-on-container-exit --build --force-recreate --exit-code-from mongo

# npm run build

