name: CI & Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 

  tests:
    name: Tests With Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      
      - name: Checkout
        uses: actions/checkout@v3     
      
      - name: Up docker containers
        run: docker compose -f docker-compose.ci.yaml up -d 
      
      - name: run tests with docker-compose
        run: docker compose -f docker-compose.ci.yaml exec -T app sh -c "npm run code:ci"
